version: "3"

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
    restart: always
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: ["npm", "run", "test"]
